NUM_EPISODES = 10 # TODO: change
MAX_STEPS = 1000 # TODO: change

YELLOW_DURATION = 3 # TODO: change
MAX_WAITING_TIME = 90 # TODO: change

NUM_ACTIONS = 4
MEMORY_SIZE = 128 # TODO: change
NUM_TRAIN_STEPS = 1024 # TODO: change
BATCH_SIZE = 32