TRAIN_MODE = True

NUM_EPISODES = 20 # TODO: change
MAX_STEPS = 1000 # TODO: change
GAMMA = 0.9

YELLOW_DURATION = 3 # TODO: change
MAX_WAITING_TIME = 90 # TODO: change

NUM_ACTIONS = 8
MEMORY_SIZE = 640 # TODO: change
NUM_TRAIN_STEPS = 20 # TODO: change
BATCH_SIZE = 32